services:
  - type: web
    name: graphguard-v2
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: GG_API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.11.6"
